### ISSUE TITLE
Plugin can only be installed using composer

### ISSUE THREAD

**Issue by musicjunk** [fabianmichael/kirby-meta#13]
Hello, I,ve installed kirby-meta on the "Starterkit" in plugin folder like described here on github. The panel-fields are shown in red with error, and the same error I get on an overlayscreen "Class "FabianMichael\Meta\PageMeta" not found". 

Any help please.
Achim

**Comment by fabianmichael** [comment]
@musicjunk Could you please provide additional information? I need your Kirby version and a screenshot of the error page (or a copy of the whole error message), because otherwise it’s very hard to find the underlaying issue.

**Comment by musicjunk** [comment]
Hello Fabian, 
the kirby version is starterkit 3.7.1.
PHP Version 8.0.1 
If I go to metadata tab for a page it shows this error.
![About us _ Mægazine](https://user-images.githubusercontent.com/1216174/181374001-b41c544a-c3a5-4891-83be-dde6cf3ecd70.png)
Well where does the wrong path is from?
There is a php-file located in kirby-meta-main>src>PageMeta.php
May be a simple misconfiguration from me?
I,ve sent you directly the access to my site.

THX

**Comment by fabianmichael** [comment]
Hi, I tested this and could replicate your error. The installation currently only works with composer, I’ll try to fix that soon.

**Comment by fabianmichael** [comment]
@musicjunk Fixed it, see https://github.com/fabianmichael/kirby-meta/releases/tag/0.1.2-beta
