### ISSUE TITLE
Installation Problem with Meta 0.2.0 using the "manual" way

### ISSUE THREAD

**Issue by j54j6** [fabianmichael/kirby-meta#20]
Hello, 

I tried to install the Kirby Meta Plugin using the manual way by dropping the plugin in the "plugins" folder.
Unfortunately there is an error while calling the Panel Site. It seems like there is another Issue with the same problem ([13](https://github.com/fabianmichael/kirby-meta/issues/13)). This issue is already closed.

My version I'm using is Meta 0.2.0. My Systemdata are the following:

The error is the same like in issue 13 but with my "newer" release.
There was an Release appended to the solution (0.1.2) this package works fine for manual installation. So it seems that I make no mistakes here :).
I tried to solve the problem but I've started today with Kirby and can't see through all the stuff yet :) 

This is the error I get:

![Kirby_Panel_error](https://user-images.githubusercontent.com/24981307/210181659-45482571-ce99-469d-bc1e-cc19cd878202.PNG)

Unlike in the other issue it seems that I am not able to visit the panel site at all, if I use the current version.

There are no Log Files mentioning this error (Apache or Kirby (DebugMode = true))
System Information:
Kirby Version: Starter-Kit 3.8.2
PHP: 8.1.13
Server: Apache

**Comment by Daandelange** [comment]
Hey, I had the same popup, you need to run `composer install` to download the dependencies.
#21 adds a note about this in the readme.

**Comment by ghost** [comment]
Does your problem persist on newer versions @j54j6? Support for installing it outside of Composer was recently added and should work out-of-the-box 😉 I guess this might be closed?

**Comment by j54j6** [comment]
Oh yes, this issue is closed ^^- I used the Composer installation method^^
