### ISSUE TITLE
Priority can not be erased

### ISSUE THREAD

**Issue by Daandelange** [fabianmichael/kirby-meta#23]
Once saved, the sitemap priority setting cannot be reset/erased so that it reverts to the default value, it has to keep a forced value. Of course we can manually set it to 0.5 as the default, but I like the "greyed-out-default-value" GUI that you made and this breaks it.

It's is a native limitation of the `range` field in Kirby, which [I requested and upgrade for on nolt](https://kirby.nolt.io/315). 

I've locally implemented a very basic extended `range` field (named `threshold`), if you wish I'm motivated in adding/contributing it into this addon by adapting it a little. (see screenshots on the link)

**Comment by fabianmichael** [comment]
@Daandelange Thanks for your input. I really think, this has to be solved within Kirby. Other fields, like the toggles field also allow for resettting the value. If you think that this is an urgent issue that could also be seen as a bug, maybe you should open a but in the Kirby repo in addition to the feature request. Please understand, that I want to keep the complexity of this plugin at a managable level and thus cannot include custom fields for this feature that I would have to maintain.

**Comment by Daandelange** [comment]
Yes, I understand, that's why I was asking. If it really bothers me I can always replace it in the blueprint with my own field :)
If so I'll post-back the handy code here until Kirby fixes it.

**Comment by fabianmichael** [comment]
👍
