### ISSUE TITLE
custom title separators

### ISSUE THREAD

**Issue by jaro-io** [fabianmichael/kirby-meta#28]
dear @fabianmichael,
still love your plugin so much. using it with every project.

this is not a bug but more of a feature request / question.. is it somehow possible to add custom title separators and extend the existing select field? would be super cool to have an option for the config, where you could add custom separator strings in an array.

thank you so much for your continuous hard work on this plugin!
best wishes,
jaro
🌻

**Comment by Daandelange** [comment]
Possible: yes. If you change the separator manually in `site.txt` (ex: `Meta-title-separator: ^_^`) you have it changed in the frontend. Then you can use [this unsupported blueprint trick](https://github.com/fabianmichael/kirby-meta/pull/21/commits/c2b4fb80486b3ce49a54880a7a4d1d44c41af738) to change the field type by a simple text field or the options of the select field.

**Comment by fabianmichael** [comment]
@jaro-io What character do you need? If other need it, we could just add it to the hardcoded list of available separators. If not, I can move the list of separators to a config variable instead. That way, it could be completely changed.

**Comment by jaro-io** [comment]
@Daandelange ahh, yes, such a great idea. i thought about changing them manually, but as this is nothing my clients can do themselves, it wasn’t an option for me. but just partially extending the meta blueprint sounds really promising!

@fabianmichael if you’d still like to add this, i guess having it in the config would be a great addition to your plugin. some of my clients want very unusual separators. this way i could easily give them options, without needing to extend blueprints.

thank you both so much!
🍃 ✨

**Comment by jaro-io** [comment]
@Daandelange just tried what you said. but with this solution i basically have to rewrite the whole group in my own blueprint, right? i mean i can’t just only extend the separator select field?

**Comment by Daandelange** [comment]
The code there worked in my setup a few days ago, extending the existing blueprint, replacing the specific field's blueprint attributes. See the `extends` line in the code, the example setup uses a Kirby shorthand for it. Of course you have to target the right field : I looked at the blueprint request that the panel page parses, to see the address of your field using the devs inspector.

**Comment by Daandelange** [comment]
> I can move the list of separators to a config variable instead. That way, it could be completely changed.

I think it would be a great addition, there's separators that I'd like to remove from the list (which is quite long already!).

**Comment by jaro-io** [comment]
@Daandelange i didn’t know until now that you could extend a blueprint, but only override a single field. so that works super well now. thank you for sharing this idea! anyway, would be nice to have a config setting for this.

**Comment by fabianmichael** [comment]
I’ve created a new release with a config option for title separators.
