### ISSUE TITLE
Page method : isIndexed

### ISSUE THREAD

**Issue by Daandelange** [fabianmichael/kirby-meta#30]
Hey Fabian,
I found it useful to have a `isIndexedByMeta` page method in my setup, you might want to merge this.
I use it to generate a site menu from the meta settings.

There's also a collection of indexed pages (you might not want this).

https://github.com/fabianmichael/kirby-meta/compare/main...Daandelange:kirby-meta:page-method-is-indexed

**Comment by fabianmichael** [comment]
Ineteresting idea, I just think we need to reconsider the name. Something like `isIndexible()` or `isVisibleToRobots()` would make a bit more sense to me, since its not really about my plugin but about search engine crawlers.

Just one question: what do you need this for?

**Comment by Daandelange** [comment]
I'm using it to generate the frontend menu, with some extra conditional exceptions to it.  
Not sure if it's robust choice to rely on meta, but it's a perfectly lazy solution that fits my needs, preventing to maintain a  2nd set of very similar settings (`excludes`, `includes`, etc...).  
I'm also gonna generate a good old "quick-access-rolldown-menu" with it.  
Plus I'd like to build a `sitemap.html` for humans.

`isIndexible` sounds nicer to me but it's also a more common "name" which might cause conflicts. Let's go for `isVisibleToRobots` which is very explicit too ?

**Comment by fabianmichael** [comment]
@Daandelange I don’t bother too much, but if we chose `isVisibleToRobots()`, we should also rename the sitemap method and all internal references to avoid confusion.

**Comment by Daandelange** [comment]
I went to change them all, but then I thought that it will add breaking changes if also renaming `SiteMeta::isPageIndexible()`, so I went for isIndexible. ;)

I think it's good to merge now.

**Comment by fabianmichael** [comment]
@Daandelange Thanks :-)
