### ISSUE TITLE
Visually nice header indentation

### ISSUE THREAD

**Issue by Daandelange** [fabianmichael/kirby-meta#31]
Hey,
I was bothered by the randomly indented header tags produced by the plugin, they didn't look nice in the source code.   
Here's a proposal for rendering it cleanly indented: https://github.com/fabianmichael/kirby-meta/compare/main...Daandelange:kirby-meta:header-indentation
*Note that the snippets code become a little less readable, but I didn't manage to do better with the original code style.*  
Also, the default indentation is two spaces `'   '`, level=2 (for `<html>` and `<header>`).

| Before | After |
|----|----|
| ![image](https://user-images.githubusercontent.com/1329784/212335001-999e3838-dff6-476d-b602-3f26c9011d6d.png) | ![image](https://user-images.githubusercontent.com/1329784/212334239-16444a10-c2e8-4d01-ba55-b5988f6ac22d.png) |

**Comment by fabianmichael** [comment]
@Daandelange I’ve been there before but it just adds unnecessary complexity. I’ll have to refuse this offer. Sorry!
