### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by ghost** [fabianmichael/kirby-meta#35]
I would love to use your plugin, unfortunately I can't install it via composer. See error message below:

`Could not find a version of package fabianmichael/kirby-meta matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.`

**Comment by ersoma** [comment]
Since there is no stable release yet, you have to specify the exact version you would like to use:
`composer require fabianmichael/kirby-meta:~0.3.0-beta`
