### ISSUE TITLE
Add PHP 8.2 support

### ISSUE THREAD

**Issue by ersoma** [fabianmichael/kirby-meta#36]
Hey!

When I tried to open the plugin under PHP 8.2 I got the following error:
<img width="491" alt="Képernyőfotó 2023-02-14 - 20 17 50" src="https://user-images.githubusercontent.com/6604988/218842817-d1c2af5d-1b00-4e73-a0ca-ae6e44819f8a.png">

This is because Dynamic Properties are deprecated under PHP 8.2 (https://php.watch/versions/8.2/dynamic-properties-deprecated). Kirby fully supports PHP 8.2 since 3.9 (https://getkirby.com/releases/3.9) and it would be amazing to use this plugin with it, under the most up-to-date environment. Would you consider supporting more recent PHP versions soon?
Thanks!

**Comment by fabianmichael** [comment]
Was already fixed, but no release yet. Just created a new one. :-)

https://github.com/fabianmichael/kirby-meta/releases/tag/0.3.1-beta

**Comment by ersoma** [comment]
Great, thanks!
Could you please add it to composer as well? https://packagist.org/packages/fabianmichael/kirby-meta here the latest is still `0.3.0-beta`.

**Comment by fabianmichael** [comment]
@ersoma done! Always forget about updating the version in composer.json …
