### ISSUE TITLE
Tab content not showing on `3.5`

### ISSUE THREAD

**Issue by owzim** [fabianmichael/kirby-meta#4]
We're stuck on `3.5` for various reasons. On `3.6` the tab content `meta: tabs/meta/site` is showing everything as expected but not on `3.5`. It's blank. No console warning, no errors. What special `3.6.` features in the blueprints are used, that are not compatible with `3.5`?

Glancing over the code, I haven't seen anything.

**Comment by fabianmichael** [comment]
@owzim The plugin uses Kirby’s dynamic blueprints extension point, which is a relatively new feature of 3.6. So it is technically impossible to make it work with earlier versions. Sorry! :-(

https://getkirby.com/docs/reference/plugins/extensions/blueprints#callback-definition

**Comment by owzim** [comment]
@fabianmichael thanks for the info
