### ISSUE TITLE
Error: Unmatched ']'

### ISSUE THREAD

**Issue by arnoson** [fabianmichael/kirby-meta#41]
https://github.com/fabianmichael/kirby-meta/blob/main/config/hooks.php#L17

**Comment by arnoson** [comment]
Of course I could also create a PR but I thought with such a small change this might be overkill

**Comment by fabianmichael** [comment]
@arnoson I already deleted the `hooks.php` file, since version 1.0.1 of the staticache plugin will likely be able to deal with the sitemap, see: https://github.com/getkirby/staticache/pull/22#discussion_r1135032081
