### ISSUE TITLE
Page model function 'metadata' not working

### ISSUE THREAD

**Issue by ghost** [fabianmichael/kirby-meta#45]
Hey there,

[this line](https://github.com/fabianmichael/kirby-meta/blob/main/src/PageMeta.php#L86) will always return `false` even if such method exists, since custom page methods don't exist on the `$page` object. Problem is line 32:

```php
// Get metadata from page, if possible
if (method_exists($this->page, 'metadata') === true) {  # << will always be false
    $this->metadata = $this->page->metadata($languageCode);
}
```

Because of this, `$page->metadata` is not populated, hence our check on line 86 never succeeds, rendering custom page method 'metadata' useless 😭 If a page method does not exist, Kirby assumes it's a `Field` with value `null` 😕 

Solution:

`hasMethod` to the rescue:

```php
// Get metadata from page, if possible
if ($this->page->hasMethod('metadata') === true) {  # << njom njom
    $this->metadata = $this->page->metadata($languageCode);
}
```

Voila! PR welcome, I guess? 🤣

**Comment by ghost** [comment]
There it is!

offtopic:
I'd like to see a new (patch) release after this getting merged, so I can further hack on your stuff in production 😆

**Comment by fabianmichael** [comment]
@CHE1RON Usually, `metadata()` is implemented on custom page models as a "real" method, so this was intentional. However, I added the possibility to use Kirby’s "virtual" methods as well, see [02f79b9](https://github.com/fabianmichael/kirby-meta/commit/02f79b9fdec0d5718f432b95f290290a6fd0270e).

**Comment by ghost** [comment]
Thanks @fabianmichael for your feedback, I totally forgot about this - but my approach should work in both situations (= no need for both checks), or am I mistaken ❓

**Comment by fabianmichael** [comment]
@CHE1RON I’ve digged through Kirby’s source and it seems like the `HasMethods` trait only searches Kirby’s built-in methods.

**Comment by ghost** [comment]
Alright, thanks for letting me know. If I can lend a hand, let me know, Discord or otherwise.
