### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by AlexanderBoenninger** [fabianmichael/kirby-meta#48]
Hey.
Got an error when tring to install via composer your plugin: 
  _Could not find a version of package fabianmichael/kirby-meta matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability._  

It sayes in PackageDiscoveryTrait.php line 331  

Using kirby 3.9.3
PHP 8.0.28

Can you reproduce that?
Do I need any other dependencies?

**Comment by j54j6** [comment]
Hey :) 

I had the same error. It seems like there is no stable version published for this repo (it is in beta state ^^) 

You can use the following command (this defines the package by its version) and it will work :)

composer require fabianmichael/kirby-meta 0.4.0-beta

Hope it works :) - Check also that you have composer 2.x installed

**Comment by fabianmichael** [comment]
@AlexanderBoenninger Please use the solution provided by @j54j6 for now. There are still some minor issues with the plugin (missing docs, translations etc.) that I want to resolve before calling it "stable".
