### ISSUE TITLE
Share preview is cut off when there are many files in files section above

### ISSUE THREAD

**Issue by hariom147** [fabianmichael/kirby-meta#6]
First of all: Thanks for your great plugins, @fabianmichael.

When there are many files in the files section above the share preview, it gets cut off because of "sticky" set on the column.
Quick solution could be to add pagination to files at maybe 10 - or an option to be able to set pagination in the config.

(Unfortunately I am not yet capable of adding the code and contributing a PR).
![Bildschirmfoto 2022-02-27 um 09 53 47](https://user-images.githubusercontent.com/8297800/155875668-3e941917-2063-42df-b72a-e4ef18d55145.png)
.

**Comment by fabianmichael** [comment]
@hariom147 I changed the order of the sidebar items, so the preview should always stay visible.
