### ISSUE TITLE
Kirby 4 compatibility?

### ISSUE THREAD

**Issue by eheiser** [fabianmichael/kirby-meta#60]
More a question than an issue.
Currently testing Kirby 4 (release candidate 2) and the plugin is working fine.
The only thing that's not working is in the control panel, if you try to access the settings window for the plugin the following error shows:
```php
FabianMichael\Meta\PageMeta::get(): Return value must be of type Kirby\Cms\Field, Kirby\Content\Field returned
``` 
Just wanted to report, thanks for putting out such a quality plugin.

**Comment by fabianmichael** [comment]
@eheiser Thanks for reporting, work on the transition has already started. My plan is to freeze the plugin as-is for 3.x and make 1.0 Kirby 4-only, since a few breaking changes might be necessary at this point.

**Comment by eheiser** [comment]
Cool, many thanks already!

**Comment by eheiser** [comment]
Any word on a release date?

**Comment by fabianmichael** [comment]
@eheiser See develop branch
