### ISSUE TITLE
exclude pages from metadata overview

### ISSUE THREAD

**Issue by jaro-io** [fabianmichael/kirby-meta#7]
dear @fabianmichael,
i would like to exclude all unlisted pages from the metadata overview. the one thats directly accessible through the hamburger menu in the panel. is there some kind of setting for this? if not, do you have a suggestion on where to add this? would also be super cool if it was possible to exclude custom pages with an array like for the sitemap config.

thank you so much for your help.
such a great plugin!
🤍 ✨

**Comment by fabianmichael** [comment]
@jaro-io Good idea. I’ll have a look into that in the near future.

**Comment by fabianmichael** [comment]
@jaro-io I just added a filter callback option allowing you to provide a callback function in config (`fabianmichael.meta.panel.view.filter`). Hope, that helps :-) Re-open if not.

**Comment by jaro-io** [comment]
@fabianmichael wow, how cool! thank you so much for your time on this! :pray: :sparkles: i was just playing around with it but couldn’t get it to work until now. can you maybe provide an example? 

this is where i am at currently for the `config.php` _(the first two settings work fine)_:

```
// seo meta plugin
'fabianmichael.meta.robots.canonical' => false,
'fabianmichael.meta.theme.color' => '#fefaf0',
'fabianmichael.meta.panel.view.filter' => function ($page) {
    return $page->intendedTemplate() != 'product';
}
```
---

if i use the filter function elsewhere it works totally fine:

```
dump($site->index()->filter(function ($page) {
    return $page->intendedTemplate() != 'product';
}));
```

**Comment by fabianmichael** [comment]
@jaro-io I’ve copied your code and tried with the templates available on my test setup. However, it worked fine for me, just like prior tests did …

**Comment by jaro-io** [comment]
:face_with_spiral_eyes:
so sorry @fabianmichael
there has been an issue with the installation on my end, which i was able to fix.

again, thank you so much for your time.
it is now working BEAUTIFULLY!
:sunflower:

**Comment by fabianmichael** [comment]
@jaro-io No worries :-)
